### PR TITLE
ARM builds

### PR DESCRIPTION
**Pull request by CRImier**
Referencing https://github.com/arduino/Arduino/pull/3549 in Arduino IDE repo - this is the script that I used to compile libastyle.

### CODE REVIEW

**Comment by cmaglie** [comment]
LGTM, I didn't actually tried it but it should not harm anyone.

**Comment by NicoHood** [comment]
Do we have a chance that someone updates the ARM PR for arduino now?

**Comment by NicoHood** [comment]
It turns out that this "someone" is me now.

I had to compile astyle for arm now. I noticed that it gave me an error if I crosscompile the file from a linux x64 distribution. I am currently searching for a solution. We somehow need to pass the arch to the compiler. I tried `-march=armv7` without success.

We should fix this, once a solution is there.

**Comment by NicoHood** [comment]
This is a solution, I just dont know how to integrate it (so linux builds dont break instead). Maybe they should add an arm folder upstream?

```
# The arm compiler is only required for cross compiling
sudo apt-get install gcc-arm-linux-gnueabi g++-arm-linux-gnueabi gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

# For cross compiling change the CXX compiler flag to:
nano ./astyle-code/AStyle/build/gcc/Makefile
CXX = arm-linux-gnueabihf-g++
```

**Comment by cmaglie** [comment]
Adding the CXX flag here https://github.com/arduino/astyle/blob/master/arm.bash may be of any help?

Something along the line of:
http://stackoverflow.com/questions/2969222/make-gnu-make-use-a-different-compiler

**Comment by NicoHood** [comment]
I tried this, but it did not seem to overwrite the setting. Maybe I did something wrong.

**Comment by ShorTie8** [comment]
I found to be able to compile it I had to set the JAVA_HOME variable some where

JAVA_HOME=`readlink -f /usr/bin/javac | sed "s:bin/javac::"`

**Comment by NicoHood** [comment]
Huh? We are talking about cross compiling. What does this have to do with selecting an arm compiler?

**Pull request merged**
